### ISSUE TITLE
GetColumnType always returns SQLITE_NULL 5?

### ISSUE THREAD

**Issue by zhengzilu** [slidertom/ds#2]
In file sqlite/SqLiteRecordsetImpl.cpp function dsFieldType CSqLiteRecordsetImpl::GetColumnType(int nCol) const{}
I think there is a problem with line 1274 . int32_t nType = sqlite3_column_type(m_stmt, nCol);
Because it always returns  SQLITE_NULL     5.
If it is not my fault, I managed to fix this problem by adding sqlite3_step(m_stmt); before line 1274.
reference : http://sqlite.1065341.n5.nabble.com/sqlite3-column-type-bad-value-td54805.html

**Comment by slidertom** [comment]
Thanks for detail info :)

fixed

**Comment by zhengzilu** [comment]
Though I don't understand how sqlite3_step(m_stmt) works, the other GetColumn* functions in SqLiteRecordsetImpl.cpp like GetFieldString, GetFieldInt32 seem to return NULL or 0 too. Statements like sqlite3_column_int(m_stmt, nColumnIndex); can not be executed correctly. I guess they all have the same issue.

**Comment by slidertom** [comment]
No I do not have an issue. It have to be used dsTable::MoveFirst call as it shown in the 
https://github.com/slidertom/ds sample. MoveFirst calls sqlite3_step or in case of dao it calls MoveFirst (https://docs.microsoft.com/en-us/cpp/mfc/reference/cdaorecordset-class?view=vs-2019#movefirst).
I've applied fix, because it looks like to be logical to query field type with out forcing to step into.
Currently I think it's a mistake. Developer always must call MoveFirst (sqlite3_step) before calling: 
GetColumnType.
(dsDatabase probably must responsible for the field type retrieve for the table and for the queries it must be used
sqlite logic)
